# Generated by Django 3.2 on 2021-04-17 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('release_date', models.CharField(max_length=250)),
                ('official_website', models.CharField(max_length=250)),
                ('developer', models.CharField(max_length=250)),
                ('publisher', models.CharField(max_length=250)),
                ('platforms', models.CharField(max_length=250)),
                ('pegi', models.CharField(max_length=250)),
                ('tags', models.CharField(max_length=250)),
            ],
        ),
    ]
