# Generated by Django 3.2 on 2021-04-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesapp', '0002_alter_game_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListGame',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('merchant', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
                ('href', models.CharField(max_length=250)),
            ],
        ),
    ]
