# Generated by Django 3.2 on 2021-04-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesapp', '0003_listgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listgame',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
